name: Update Rebrickable Catalog

on:
  schedule:
    - cron: '0 0 * * 1,4' # Lundi et Jeudi
  workflow_dispatch: # Déclenchement manuel

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Téléchargement et extraction des CSV
        run: |
          mkdir -p data
          
          # On télécharge dans un dossier temporaire d'abord
          mkdir -p temp_dl
          cd temp_dl
          
          wget -q https://cdn.rebrickable.com/media/downloads/themes.csv.zip
          wget -q https://cdn.rebrickable.com/media/downloads/sets.csv.zip
          wget -q https://cdn.rebrickable.com/media/downloads/minifigs.csv.zip
          
          unzip -q -o themes.csv.zip
          unzip -q -o sets.csv.zip
          unzip -q -o minifigs.csv.zip
          
          rm *.zip
          
          # On déplace les nouveaux CSV vers le dossier suivi par Git
          mv *.csv ../data/
          cd ..
          rm -rf temp_dl

      - name: Vérification des changements
        id: check_changes
        run: |
          # Git status -s affiche les fichiers modifiés.
          # Si la sortie est vide, rien n'a changé.
          if [[ -n $(git status -s data/*.csv) ]]; then
            echo "Des modifications ont été détectées dans les CSV."
            echo "has_changes=true" >> $GITHUB_OUTPUT
            
            # UNIQUEMENT SI CA A CHANGÉ : On génère la nouvelle version
            echo "{\"last_updated\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > data/version.json
          else
            echo "Aucun changement détecté dans les catalogues Rebrickable."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit et Push (Si changements détectés)
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add data/
          git commit -m "Mise à jour automatique : Nouveaux sets ou thèmes détectés"
          git push
